### ISSUE TITLE
curl带换行符，input()读不完。

### ISSUE THREAD

**Issue by csjue** [BakaFT/XuetangX-AutoAnswering#1]
main.py 第十一行

**Comment by BakaFT** [comment]
做的时候没想到这个问题，我在Windows Terminal是没问题的。。
可以手动去一下换行符或者百度找一下解决方案改写以下代码

还有，这玩意现在还能用。。？

**Comment by csjue** [comment]
还可以。

**Comment by BakaFT** [comment]
> 还可以。

学堂在线是真不上心。。
我懒得改代码了orz 大佬用的话照自己习惯随手改改用吧
